In [1]:
import pandas as pd
import warnings

warnings.filterwarnings('ignore')

df = pd.read_csv('D:\Area de trabalho\Faculdade\BioData\Q-Cyber\QML\data\ML-EdgeIIoT-dataset.csv')
df.head()

<>:6: SyntaxWarning: invalid escape sequence '\A'
<>:6: SyntaxWarning: invalid escape sequence '\A'
C:\Users\loqui\AppData\Local\Temp\ipykernel_9180\332393840.py:6: SyntaxWarning: invalid escape sequence '\A'
  df = pd.read_csv('D:\Area de trabalho\Faculdade\BioData\Q-Cyber\QML\data\ML-EdgeIIoT-dataset.csv')

,frame.time,ip.src_host,ip.dst_host,arp.dst.proto_ipv4,arp.opcode,arp.hw.size,arp.src.proto_ipv4,icmp.checksum,icmp.seq_le,icmp.transmit_timestamp,...,mqtt.proto_len,mqtt.protoname,mqtt.topic,mqtt.topic_len,mqtt.ver,mbtcp.len,mbtcp.trans_id,mbtcp.unit_id,Attack_label,Attack_type
0,6.0,192.168.0.152,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,MITM
1,6.0,192.168.0.101,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,MITM
2,6.0,192.168.0.152,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,MITM
3,6.0,192.168.0.101,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,MITM
4,6.0,192.168.0.152,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,MITM

In [2]:
numerical_col = []
categorical_col = []

for i in df.columns:
    if df[i].nunique() == 1: 
        df.drop(i , axis =1 , inplace = True)
        print("dropped column : ", i)
    
    elif i != 'Attack_label' or i != 'Attack_type':
        if df[i].dtype == object or df[i].nunique() <= 20:
            categorical_col.append(i)
        else:
            numerical_col.append(i)

traget_col = ['Attack_label', 'Attack_type']
print(f"Colunas target: {traget_col}") 
print(f"Colunas categóricas: {categorical_col}")
print(f"Colunas numéricas {numerical_col}")

dropped column :  icmp.unused
dropped column :  http.tls_port
dropped column :  dns.qry.type
dropped column :  dns.retransmit_request_in
dropped column :  mqtt.msg_decoded_as
dropped column :  mbtcp.len
dropped column :  mbtcp.trans_id
dropped column :  mbtcp.unit_id
Colunas target: ['Attack_label', 'Attack_type']
Colunas categóricas: ['frame.time', 'ip.src_host', 'ip.dst_host', 'arp.dst.proto_ipv4', 'arp.opcode', 'arp.hw.size', 'arp.src.proto_ipv4', 'http.file_data', 'http.request.uri.query', 'http.request.method', 'http.referer', 'http.request.full_uri', 'http.request.version', 'http.response', 'tcp.connection.fin', 'tcp.connection.rst', 'tcp.connection.syn', 'tcp.connection.synack', 'tcp.flags', 'tcp.flags.ack', 'tcp.options', 'tcp.payload', 'tcp.srcport', 'dns.qry.name.len', 'dns.retransmission', 'dns.retransmit_request', 'mqtt.conack.flags', 'mqtt.conflag.cleansess', 'mqtt.conflags', 'mqtt.hdrflags', 'mqtt.len', 'mqtt.msg', 'mqtt.msgtype', 'mqtt.proto_len', 'mqtt.protoname', 'mqtt.topic', 'mqtt.topic_len', 'mqtt.ver', 'Attack_label', 'Attack_type']
Colunas numéricas ['icmp.checksum', 'icmp.seq_le', 'icmp.transmit_timestamp', 'http.content_length', 'tcp.ack', 'tcp.ack_raw', 'tcp.checksum', 'tcp.dstport', 'tcp.len', 'tcp.seq', 'udp.port', 'udp.stream', 'udp.time_delta', 'dns.qry.name', 'dns.qry.qu']

In [3]:
zero_percent_columns = []

for col in df.columns:
    try:
        zero_ratio = (df[col] == 0).sum() / len(df)
        if zero_ratio >= 0.50:
            zero_percent_columns.append((col, zero_ratio))
            df.drop(col , axis=1 , inplace=True)
    except:
        # Skip non-numeric or problematic columns
        continue

# Display the results
for col, ratio in zero_percent_columns:
    print(f"{col}: {ratio:.2%} zeros")

print("number of dropped columns: " ,len(zero_percent_columns))
print("New DF Shape: ", df.shape)

arp.opcode: 99.00% zeros
arp.hw.size: 99.00% zeros
icmp.checksum: 90.70% zeros
icmp.seq_le: 90.08% zeros
icmp.transmit_timestamp: 99.95% zeros
http.content_length: 94.01% zeros
http.request.uri.query: 58.47% zeros
http.referer: 68.85% zeros
http.response: 95.43% zeros
tcp.connection.fin: 94.19% zeros
tcp.connection.rst: 90.59% zeros
tcp.connection.syn: 87.21% zeros
tcp.connection.synack: 97.01% zeros
tcp.len: 73.19% zeros
udp.port: 99.74% zeros
udp.stream: 90.79% zeros
udp.time_delta: 99.74% zeros
dns.qry.name: 98.95% zeros
dns.qry.name.len: 89.47% zeros
dns.qry.qu: 99.84% zeros
dns.retransmission: 99.98% zeros
dns.retransmit_request: 100.00% zeros
mqtt.conack.flags: 79.23% zeros
mqtt.conflag.cleansess: 99.21% zeros
mqtt.conflags: 99.21% zeros
mqtt.hdrflags: 96.79% zeros
mqtt.len: 97.60% zeros
mqtt.msg: 79.23% zeros
mqtt.msgtype: 96.79% zeros
mqtt.proto_len: 99.21% zeros
mqtt.protoname: 79.23% zeros
mqtt.topic: 79.23% zeros
mqtt.topic_len: 99.21% zeros
mqtt.ver: 99.21% zeros
number of dropped columns:  34
New DF Shape:  (157800, 21)

In [4]:
drop_columns = [
    "frame.time",            # Date and time (Alta cardialidade)
    "ip.src_host",           # Source Host (Alta cardialidade)
    "ip.dst_host",           # Destination Host (Alta cardialidade)
    "arp.dst.proto_ipv4",    # Target IP address (Alta cardialidade)
    "arp.src.proto_ipv4",    # Sender IP address (Alta cardialidade)
    "http.file_data",        # File Data (raw content, unstructured string/bytes)
    "http.request.method",   # HTTP method (likely has little variation; use only if modeling request types)
    "http.request.full_uri", # Full request URI (very high cardinality string, likely unique per request)
    "http.request.version",  # HTTP version (may have little variance and minimal predictive value)
    "tcp.dstport",           # Destination Port (label type, likely high cardinality or redundant with `tcp.srcport`)
    "tcp.options",           # TCP Options (Alta cardialidade - sequence of bytes, not directly useful without custom parsing)
    "tcp.payload",           # TCP Payload (Alta cardialidade - Dado não estruturado)
    "tcp.srcport"            # Source Port (unsigned int, possibly high cardinality, often randomized)
]

#df.drop(drop_columns, axis=1, inplace=True)
df.shape

(157800, 21)

In [5]:
objList = df.select_dtypes(include = "object").columns
objList

Index(['frame.time', 'ip.src_host', 'ip.dst_host', 'arp.dst.proto_ipv4',
       'arp.src.proto_ipv4', 'http.file_data', 'http.request.method',
       'http.request.full_uri', 'http.request.version', 'tcp.options',
       'tcp.payload', 'tcp.srcport', 'Attack_type'],
      dtype='object')

In [6]:
df = df[df["Attack_label"] != "Normal"]

In [7]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()

for obj in objList:
    df[obj] = encoder.fit_transform(df[obj].astype(str))

In [8]:
df.columns

Index(['frame.time', 'ip.src_host', 'ip.dst_host', 'arp.dst.proto_ipv4',
       'arp.src.proto_ipv4', 'http.file_data', 'http.request.method',
       'http.request.full_uri', 'http.request.version', 'tcp.ack',
       'tcp.ack_raw', 'tcp.checksum', 'tcp.dstport', 'tcp.flags',
       'tcp.flags.ack', 'tcp.options', 'tcp.payload', 'tcp.seq', 'tcp.srcport',
       'Attack_label', 'Attack_type'],
      dtype='object')

In [9]:
objList = objList.drop(['Attack_type'])
df_cleaned = df.drop(objList, axis=1)
df_cleaned.dtypes

tcp.ack          float64
tcp.ack_raw      float64
tcp.checksum     float64
tcp.dstport      float64
tcp.flags        float64
tcp.flags.ack    float64
tcp.seq          float64
Attack_label       int64
Attack_type        int64
dtype: object

In [10]:
df_cleaned["Attack_label"].value_counts()

Attack_label
1    133499
0     24301
Name: count, dtype: int64

In [12]:
decoded_features_Attack_type = encoder.inverse_transform(df_cleaned["Attack_type"])
print(f"Decoded Attack_type: {decoded_features_Attack_type}")

Decoded Attack_type: ['MITM' 'MITM' 'MITM' ... 'DDoS_ICMP' 'DDoS_ICMP' 'DDoS_ICMP']

In [17]:
import numpy as np

np.unique(decoded_features_Attack_type)

array(['Backdoor', 'DDoS_HTTP', 'DDoS_ICMP', 'DDoS_TCP', 'DDoS_UDP',
       'Fingerprinting', 'MITM', 'Normal', 'Password', 'Port_Scanning',
       'Ransomware', 'SQL_injection', 'Uploading',
       'Vulnerability_scanner', 'XSS'], dtype=object)

In [10]:
df_cleaned["Attack_type"]

0         6
1         6
2         6
3         6
4         6
         ..
157795    2
157796    2
157797    2
157798    2
157799    2
Name: Attack_type, Length: 157800, dtype: int64

In [11]:
from sklearn.model_selection import train_test_split

X, X_test, y, y_test = train_test_split(df_cleaned, df_cleaned["Attack_type"], test_size=0.2, random_state=42)

In [12]:
X_test.iloc[:2]

,tcp.ack,tcp.ack_raw,tcp.checksum,tcp.dstport,tcp.flags,tcp.flags.ack,tcp.seq,Attack_label,Attack_type
23552,354.0,2.504429e+09,64954.0,37160.0,17.0,1.0,478.0,1,11
31814,479.0,1.761562e+09,41803.0,80.0,16.0,1.0,354.0,1,11

In [13]:
X_test.to_csv("./../data/dados_de_teste.csv", index=False)